apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    chart: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: helloworld
  selector:
    app: {{ .Values.appName }}
