apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    chart: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
    name: {{ .Values.appName }}
  selector:
    app: {{ .Values.appName }}
