apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: helloworld
      spec:
        containers:
        - name: helloworld
          image: msazurestackdocker/linsuhyperkube:v1
          ports:
          - containerPort: 80
